# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-24517-ntnumalt/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg484-1

    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/verilog-blackbox/BRAM64x1024.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/verilog-blackbox/BRAM64x2048.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/verilog-blackbox/BRAM64x4096.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/verilog-blackbox/BRAM64x8192.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/verilog-blackbox/BRAM64x16384.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/verilog-blackbox/BRAM64x32768.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/verilog-blackbox/BRAM64x65536.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/chisel-wrappers/WrapperBRAM64x1024.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/chisel-wrappers/WrapperBRAM64x2048.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/chisel-wrappers/WrapperBRAM64x4096.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/chisel-wrappers/WrapperBRAM64x8192.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/chisel-wrappers/WrapperBRAM64x16384.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/chisel-wrappers/WrapperBRAM64x32768.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/chisel-wrappers/WrapperBRAM64x65536.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/verilog-blackbox/CustomQueue32x1024.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/verilog-blackbox/CustomQueue32x256.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/verilog-blackbox/CustomQueue32x512.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/verilog-blackbox/CustomQueue64x1024.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/verilog-blackbox/CustomQueue64x256.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/verilog-blackbox/CustomQueue64x512.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/chisel-wrappers/WrapperCustomQueue32x1024.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/chisel-wrappers/WrapperCustomQueue32x256.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/chisel-wrappers/WrapperCustomQueue32x512.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/chisel-wrappers/WrapperCustomQueue64x1024.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/chisel-wrappers/WrapperCustomQueue64x256.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/chisel-wrappers/WrapperCustomQueue64x512.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/verilog-blackbox/XilinxDPAdd4Stage_stub.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/verilog-blackbox/XilinxDPMul4Stage_stub.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/chisel-wrappers/WrapperXilinxDPAdd4Stage.v
      /home/maltanar/Dropbox/PhD/ip-repo/ZynqWrappers/chisel-wrappers/WrapperXilinxDPMul4Stage.v
      /home/maltanar/sandbox/spmv-vector-cache/chisel/verilogOutput/SpMVAccel-BufferNone/AXIAccelWrapper.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top AXIAccelWrapper
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter repFanoutThreshold 500
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
    rt::set_parameter earlyMaximalSharing false
    rt::set_parameter webTalkPath {./.Xil/Vivado-24517-ntnumalt/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-24517-ntnumalt/"
    if {$rt::useElabCache == false} {
      rt::run_synthesis -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
